config/routes.rb
Genesis::Application.routes.draw do
  resources :customers do
    collection do
       get ':id/destroy_asset', :action => 'destroy_asset', :as => 'asset_destroy'
     end
   end
    
  devise_for :users  do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  

    root :to => 'customers#new'

end

app/models/appraisal.rb
class Appraisal < ActiveRecord::Base
  belongs_to :customer
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :customer
  
  has_attached_file :asset
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :borrower, :presence => true
  has_one :loi
  has_one :appraisal
  has_one :environmental
  has_one :loandetail
  has_many :subborrowers
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :loi, :appraisal, :environmental, :loandetail, :subborrowers, :assets
end

app/models/environmental.rb
class Environmental < ActiveRecord::Base
  belongs_to :customer
end

app/models/loandetail.rb
class Loandetail < ActiveRecord::Base
  belongs_to :customer
end

app/models/loi.rb
class Loi < ActiveRecord::Base
  belongs_to :customer
end

app/models/subborrower.rb
class Subborrower < ActiveRecord::Base
  belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
before_filter :authenticate_user!
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new
    3.times do
      @customer.subborrowers.build
    end
    
    30.times do
      @customer.assets.build
    end
    
    @customer.build_loi
    @customer.build_appraisal
    @customer.build_environmental
    @customer.build_loandetail

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
    
    @number_of_existing_uploads = get_number_of_existing_uploads
    @customer.assets.build
  end
  
  def get_number_of_existing_uploads
    number_of_existing_uploads = 0
    
    @customer.assets.each do |asset|
      number_of_existing_uploads += 1 unless asset.asset_file_name.nil?
    end  
    
    return number_of_existing_uploads
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
  
  def destroy_asset
    @customer = Customer.find(params[:id])
    Asset.delete(params[:asset_id])
    
    respond_to do |format|
      format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }  
    end
  end
  
end

app/controllers/lois_controller.rb
class LoisController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/lois_helper.rb
module LoisHelper
end

app/views/customers/_form.html.erb
<div class="depot_form">
<%= form_for(@customer, :html => { :multipart => true }) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <legend>Enter Borrower Details</legend>
<table>
<tr> 
 <td>
  <div class="field">
    <%= f.label :borrower, ' Borrower Name:' %><br />
    <%= f.text_field :borrower, size: 60  %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= f.label :address_b, 'Address:' %><br />
    <%= f.text_field :address_b, size: 60 %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= f.label :city_b, 'City:' %><br />
    <%= f.text_field :city_b %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= f.label :state_b, 'State:' %><br />
    <%= f.text_field :state_b %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= f.label :zipcode_b, 'Zip code:' %><br />
    <%= f.text_field :zipcode_b %>
  </div> 
 </td>
</tr>
<tr>
  <td>
  <div class="field">
    <%= f.label :businessname, 'Business Name:' %><br />
    <%= f.text_field :businessname, size: 60  %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :businesstype, 'Business Type:' %><br />
    <%= f.text_field :businesstype, size: 60 %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :ownership, 'Ownership%:' %><br />
    <%= f.text_field :ownership %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :loanamount, 'Loan Amount:' %><br />
    <%= f.text_field :loanamount %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :ltv, 'LTV:' %><br />
    <%= f.text_field :ltv %>
  </div>
  </td>
 </tr>
 <tr>
  <td>
  <div class="field">
    <%= f.label :transactiontype, 'Transaction Type:' %><br />
    <%= f.text_field :transactiontype, size: 60 %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :address_g, 'Property Address:' %><br />
    <%= f.text_field :address_g, size: 60  %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :city_g, 'City:' %><br />
    <%= f.text_field :city_g %>
  </div>
  </td> 
  <td>
  <div class="field">
    <%= f.label :state_g, 'State:' %><br />
    <%= f.text_field :state_g %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :zipcode_g, 'Zip Code:' %><br />
    <%= f.text_field :zipcode_g %>
  </div>
  </td>
 </tr>
</table>

<table>
 
 	<%= f.fields_for :subborrowers do |ff| %>
    <tr>
    <td>
		<div> Co Borrower Name: </div>
		<div><%= ff.text_field :name, size: 60 %>
	</td>
	<td>
		<div> Address: </div>
		<div><%= ff.text_field :address, size: 60 %>
	</td>
	<td>
		<div> City: </div>
		<div><%= ff.text_field :city %>
	</td>
	<td>
		<div> State: </div>
		<div><%= ff.text_field :state %>
	</td>
	<td>
		<div> Zip code: </div>
		<div><%= ff.text_field :zip %>
	</td>
	</tr>
 	<% end %>
 
</table>



 <h4>Loan Details</h4>
<table cellspacing="20">
  <tr>
	<td>
  	<%= f.fields_for :loi do |ff| %>   
    	<div> LOI Issued Date:</div> 
    	<div><%= ff.text_field :issued_date %></div>
	 	<div> LOI Accepted Date: </div>
	 	<div> <%= ff.text_field :accepted_date %></div>  
  	<% end %> 
    </td>
    <td>
  	<%= f.fields_for :appraisal do |ff| %>
    	<div>Appraisal Ordered Date:</div>
    	<div><%= ff.text_field :ordered_date %></div>
    	<div>Appraisal received Date:</div>
    	<div><%= ff.text_field :received_date %></div>
  	<% end %>
   </td>
   <td>
  	<%= f.fields_for :environmental do |ff| %>
    	<div>Env Ordered Date:</div>
    	<div><%= ff.text_field :ordered_date %>
		<div>Env Received Date: </div>
		<div><%= ff.text_field :received_date %>
  	<% end %>
    </td>
  
  	<td>
  	<%= f.fields_for :loandetail do |ff| %>
  		<div>Deposit Made Date:</div>
    	<div><%= ff.text_field :deposit_date %>
		<div>Docs Ordered Date: </div>
		<div><%= ff.text_field :docs_ordered_date %>
	</td>
	<td>
		<div>Funded Date: </div>
		<div><%= ff.text_field :funded_date %>
		<div>Name of Broker: </div>
		<div><%= ff.text_field :broker %>
	</td>
   </tr>
   <tr>
	<td>
	<div>Commission: </div>
	<div><%= ff.text_field :commission %>
	</td>	
  <% end %>
 </tr>
</table>

<h4>Uploaded Documents (<%= @number_of_existing_uploads %>)</h4>
<% type_array = [['Tax Return (last yr)','tax return last yr'],['Tax Return (prev yr)','tax return prev yr'],
	    ['Tax Return (prev 2 yrs)','tax return prev 2 yrs'],['Guarantor Tax Return (last yr)','guarantor tax return (last yr)'],
		['Guarantor Tax Return (prev yr)','guarantor tax return (prev yr)'],['Guarantor Tax Return (Prev 2 yrs)','guarantor tax return (prev 2 yrs)'],
		['Financial Statement within 90 Days','financial statement within 90 days'],['Affiliated Tax Return (last yr)','affiliated tax return (last yr)'],
		['Affiliated Financial Statement 90 days','affiliated financial statement 90 days'],['Affiliated Tax Return (prev yr)','affiliated tax return (prev yr)'],
		['Affiliated Tax Return (2 yrs)','affiliated tax return (2 yrs)'],['Projection', 'projection'],['Resume','resume'],['SBA 912 - Statement','sba 912 - statement'],
		['SBA 413 - Personal Financial Statement','sba 413 - personal financial statement'],['T4506 - IRS Transcript','T4506 - IRS transcript'],
		['INS Form G845','ins form g845'],['Purchase & Sales Agreement','purchase & sales agreement'],['Lease Agreement','lease agreement'],
		['Business Fact Sheet','business fact sheet'],['Business Debt Schedule','business debt schedule'],['Corporate Document','corporate document'],
		['Equipment List','equipment list'],['Franchise/Gas Supplier Agreement','franchise/gas supplier agreement'],['Personal Credit Report','personal credit report'],
		['Monthly ADR/Monthly Gallon & Inside Report','monthly adr/monthly gallon & inside report'],['Bank Statement','bank statement'],['Other','other']] %>
<!-- Display already uploaded files -->
<table>
<%= f.fields_for :assets do |ff| %>
	<% file_name = ff.object.asset_file_name %>
	<tr>
	<% if !file_name.nil? %>
		<td><%= ff.select :docname, type_array %></td>   
		<td><%= file_name %></td>   <td></td>
		<td><%= link_to "View File", ff.object.asset.url %> | </td>
		<td><%= link_to "Delete File", asset_destroy_customers_path(:asset_id => ff.object.id) %></td>
	
	<% end %>
	</tr>
<% end %>
</table>
<h4>Upload New Documents</h4>
<!-- Display already uploaded files -->
<%= f.fields_for :assets do |ff| %>
	<% file_name = ff.object.asset_file_name %>
	<% if file_name.nil? %>
		<%= ff.select :docname, type_array %>    
		<%= ff.file_field :asset %>
	<br />
	<% end %>
<% end %>



 <br />
<br />
<div class="actions">
    <%= f.submit %>
  </div>
 </fieldset>
 <% end %>

</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing SBA customers</h1>

<table border="1">
  <tr>
   <th>Borrower Name</th>
   <th>Business Name</th>
   <th>Business Type</th>
   <th>Ownership %</th>
   <th>Loan Amount</th>
   <th>LTV</th>
   <th>Transaction Type</th>
   <th>LOI Issued Date</th>
   <th>LOI Accepted Date</th>
   <th>Action</th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.borrower %></td>
    
    <td><%= customer.businessname %></td>
    <td><%= customer.businesstype %></td>
    <td><%= customer.ownership %></td>
    <td><%= customer.loanamount %></td>
    <td><%= customer.ltv %></td>
    <td><%= customer.transactiontype %></td>
    
    <td><%= customer.loi.issued_date %>
	<td><%= customer.loi.accepted_date %>
    <td><%= link_to 'Show', customer %> | 
    <%= link_to 'Edit', edit_customer_path(customer) %> | 
    <%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New SBA Borrower </h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Loan Details</h2>
<p>
  <b>Borrower:</b>
  <%= @customer.borrower %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address_b %>
</p>

<p>
  <b>City:</b>
  <%= @customer.city_b %>
</p>

<p>
  <b>State:</b>
  <%= @customer.state_b %>
</p>

<p>
  <b>Zip code:</b>
  <%= @customer.zipcode_b %>
</p>

<p>
  <b>Business Name:</b>
  <%= @customer.businessname %>
</p>

<p>
  <b>Business Type:</b>
  <%= @customer.businesstype %>
</p>

<p>
  <b>Ownership %:</b>
  <%= @customer.ownership %>
</p>

<p>
  <b>Loan amount:</b>
  <%= @customer.loanamount %>
</p>

<p>
  <b>LTV:</b>
  <%= @customer.ltv %>
</p>

<p>
  <b>Transaction Type:</b>
  <%= @customer.transactiontype %>
</p>

<p>
  <b>Guarantor Address:</b>
  <%= @customer.address_g %>
</p>

<p>
  <b>City:</b>
  <%= @customer.city_g %>
</p>

<p>
  <b>State:</b>
  <%= @customer.state_g %>
</p>

<p>
  <b>Zip code:</b>
  <%= @customer.zipcode_g %>
</p>

<p>
  <b>LOI Issued Date:</b>
  <%= @customer.loi.issued_date %>
</p>

<p>
  <b>LOI Accepted Date:</b>
  <%= @customer.loi.accepted_date %>
</p>

<p>
  <b>Appraisal Ordered Date:</b>
  <%= @customer.appraisal.ordered_date %>
</p>

<p>
  <b>Appraisal Received Date:</b>
  <%= @customer.appraisal.received_date %>
</p>

<p>
  <b>Environmental Ordered Date:</b>
  <%= @customer.environmental.ordered_date %>
</p>

<p>
  <b>Environmental Received Date:</b>
  <%= @customer.environmental.received_date %>
</p>

<p>
  <b>Deposit Made Date:</b>
  <%= @customer.loandetail.deposit_date %>
</p>

<p>
  <b>Docs Ordered Date:</b>
  <%= @customer.loandetail.docs_ordered_date %>
</p>

<p>
  <b>Funded Date:</b>
  <%= @customer.loandetail.funded_date %>
</p>

<p>
  <b>Name of Broker:</b>
  <%= @customer.loandetail.broker %>
</p>

<p>
  <b>Commission:</b>
  <%= @customer.loandetail.commission %>
</p>

<h4>Uploaded Documents:</h4>
<table>
<% @customer.assets.each do |asset|%>
   <tr>
	<% file_name = asset.asset_file_name %>
	<% if !file_name.nil?%>
		<td>=> <%= file_name %></td>
		<td></td>
		<td><%= link_to "View File", asset.asset.url %></td>
	<% end %> 
	</tr>		
<% end %>
</table>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
  <title>genesis online loan managment tool</title>
<!-- END_HIGHLIGHT -->
  <%= stylesheet_link_tag "application" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag "application" %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
  <div id="banner">
 <!--   <%= image_tag("logo.png") %> -->
    <%= @page_title || "Genesis" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Questions</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Contact</a></li>
		<% if user_signed_in? %>
	    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
	 	<% end %>
      </ul>
    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>